# I do not claim to be good at makefiles...
# However, I can make them functional.

# I'm not commenting this one.

compile:
	gcc -o cmdlineargs -Wall -Wextra -pedantic-errors -Wstrict-prototypes -Werror main.c

clean:
	rm cmdlineargs
