# I do not claim to be good at makefiles...
# However, I can make them functional.

# Also, for this example, I have it not echo
# the commands to the console, so you just see
# the program say "Hello, World".

make:

# Compiles the code
	@gcc main.c

# Runs the code
	@./a.out

# Removes the 
	@rm a.out